version: '3'

services:
    ts-node:
        container_name: satisfactory-docs.json.ts--ts-node
        image: node:21-alpine
        restart: unless-stopped
        environment:
            NODE_OPTIONS: "--enable-source-maps --no-warnings=ExperimentalWarning --loader ts-node/esm"
        volumes:
            - .:/app/
            - ${HOME}/.npm/:/.npm/
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        user: ${USER}
        working_dir: /app/
        tty: true
    node:
        container_name: satisfactory-docs.json.ts--node
        image: node:21-alpine
        restart: unless-stopped
        volumes:
            - .:/app/
            - ${HOME}/.npm/:/.npm/
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        user: ${USER}
        working_dir: /app/
        tty: true
